<?php

namespace T2SA\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends EntityRepository
{
}
