services:
#    koolawa_apps.example:
#        class: Koolawa\AppsBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    ldap.listener:
        class: Koolawa\AppsBundle\EventListener\LdapSecuritySubscriber
        arguments: ['@doctrine']
        tags:
            - {name: kernel.event_subscriber}
